name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  #
  # Build common library
  #
  common-library-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Debug", "Release"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          dotnet build src/Chainblocks.sln -c ${{ matrix.build-type }}
      - name: Upload artifact
        if: ${{ matrix.build-type == 'Release' }}
        uses: actions/upload-artifact@v2
        with:
          name: common-library-build-${{ matrix.build-type }}
          path: |
            src/Fragcolor.Chainblocks.Common/bin/${{ matrix.build-type }}/*.nupkg
            src/Fragcolor.Chainblocks.Common/bin/${{ matrix.build-type }}/*.snupkg
          if-no-files-found: error

  #
  # Build Monogame sample
  #
  monogame-sample-build:    
    needs: common-library-build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup nuget local source
        run: |
          dotnet nuget add source "${{ github.workspace }}\Nuget_Source" -n "Local"
      - name: Download common library
        uses: actions/download-artifact@v2
        with:
          name: common-library-build-Release
          path: Nuget_Source
      - name: Build
        run: |
          dotnet build Monogame/MyGame.sln -c Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Monogame-build
          path: |
            Monogame/bin/Release/
          if-no-files-found: error

  #
  # Build Stride sample
  #
  stride-sample-build:    
    needs: common-library-build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Setup nuget local source
        run: |
          dotnet nuget add source "https://packages.stride3d.net/nuget" -n "Stride"
          dotnet nuget add source "${{ github.workspace }}\Nuget_Source" -n "Local"
      - name: Download common library
        uses: actions/download-artifact@v2
        with:
          name: common-library-build-Release
          path: Nuget_Source
      - name: Build
        run: |
          dotnet build Stride/MyGame.sln -c Release --no-self-contained
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Stride-build
          path: |
            Stride/Bin/
          if-no-files-found: error
