name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  #
  # Build common library
  #
  common-library-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Debug", "Release"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          dotnet build src/Chainblocks.sln -c ${{ matrix.build-type }}
      - name: Upload artifact
        if: ${{ matrix.build-type == 'Release' }}
        uses: actions/upload-artifact@v2
        with:
          name: common-library-build-${{ matrix.build-type }}
          path: |
            src/Fragcolor.Chainblocks.Common/bin/${{ matrix.build-type }}/*.nupkg
            src/Fragcolor.Chainblocks.Common/bin/${{ matrix.build-type }}/*.snupkg
          if-no-files-found: error
