name: claymore

on:
  workflow_call:
    inputs:
      bitness:
        default: 64bits
        required: false
        type: string

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Debug", "Release"]
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          if [ "${{ inputs.bitness }}" == "64bits" ]
          then
            echo "::set-output name=msystem::MINGW64"
            echo "::set-output name=arch::x86_64"
            echo "::set-output name=artifact::claymore-win64"
          else
            echo "::set-output name=msystem::MINGW32"
            echo "::set-output name=arch::i686"
            echo "::set-output name=artifact::claymore-win32"
          fi
      - name: Checkout claymore
        uses: actions/checkout@v2
        with:
          repository: fragcolor-xyz/claymore
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 1
          submodules: recursive
          path: claymore
      - name: Checkout chainblocks
        uses: actions/checkout@v2
        with:
          repository: fragcolor-xyz/chainblocks
          fetch-depth: 1
          submodules: recursive
          path: chainblocks
      - name: Set up rust
        env:
          RUSTUP_USE_CURL: 1
        run: |
          rustup update
          rustup default stable-${{ steps.setup.outputs.arch }}-pc-windows-gnu
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.build-type }}
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ steps.setup.outputs.msystem }}
          release: false
          path-type: inherit
          install: >-
            base-devel
            mingw-w64-${{ steps.setup.outputs.arch }}-toolchain
            mingw-w64-${{ steps.setup.outputs.arch }}-cmake
            mingw-w64-${{ steps.setup.outputs.arch }}-boost
            mingw-w64-${{ steps.setup.outputs.arch }}-ninja
            mingw-w64-${{ steps.setup.outputs.arch }}-clang
            mingw-w64-${{ steps.setup.outputs.arch }}-lld
            wget
      - name: Build (Release)
        if: ${{ matrix.build-type == 'Release' }}
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd claymore
          cargo build --release -p claymore
      - name: Build (Debug)
        if: ${{ matrix.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: 1
        shell: msys2 {0}
        run: |
          cd claymore
          cargo build -p claymore
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.artifact }}-${{ matrix.build-type }}
          path: claymore/target/${{ matrix.build-type }}/claymore.dll
          if-no-files-found: error
